theme: minima
title: Song song song
author: Sazila
email: sazila@domain.com
description: > # this means to ignore newlines until "baseurl:"
  AWESOME DESCRIPTION：佛如此，难言表~~
  
  just use mind to imagine。。
# social links
twitter_username: sazila # DO NOT include the @ character, or else the build will fail!
github_username:  sazila # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
